### ISSUE TITLE
Exception with array fieldnames

### ISSUE THREAD

**Issue by goszowski** [photogabble/laravel-remember-uploads#15] opened 2018-03-02 09:47 UTC
<img width="1439" alt="remember-file-error" src="https://user-images.githubusercontent.com/10208931/36893086-7757077c-1e0f-11e8-9967-415f7b455738.png">

**Comment by goszowski** [comment] 2018-03-02 09:49
my name of field is "image[1]"

**Comment by carbontwelve** [comment] 2018-03-02 13:53
I'll look into this.

> `@todo there is likely a bug here when $file is an array and not an UploadedFile... write unit test`

Heh, looks like I had seen this coming at the time I wrote the library but forgot to complete the functionality. Working on it now and have just created a test (671d310fa30bfabe52fe22918016597e98b53c8a) that duplicates the bug.

**Comment by carbontwelve** [comment] 2018-03-07 13:06
@goszowski I have written a bugfix for this and pushed it to the 1.3.0 pre-release here: https://github.com/photogabble/laravel-remember-uploads/releases/tag/1.3.0-alpha

**Comment by goszowski** [comment] 2018-03-08 16:23
@carbontwelve I will explain the matter in more detail.

<img width="875" alt="screenshot at 08 18-17-18" src="https://user-images.githubusercontent.com/10208931/37162123-24acb8f8-22fd-11e8-8a01-7ec16901cccb.png">
<img width="665" alt="screenshot at 08 18-21-31" src="https://user-images.githubusercontent.com/10208931/37162297-90e42d08-22fd-11e8-9822-d6862700b680.png">

Maybe I do not understand what, but if my field is in the array, I get an error.

**Comment by carbontwelve** [comment] 2018-03-09 10:07
@goszowski it looks like you may not be running with the 1.3.0-dev branch. Your screenshot of the code for RememberFileUploads.php is from master which is different from https://github.com/photogabble/laravel-remember-uploads/blob/1.3.0-dev/src/Middleware/RememberFileUploads.php

**Comment by goszowski** [comment] 2018-03-09 10:48
And now I have next problem:

![image](https://user-images.githubusercontent.com/10208931/37203928-05f88518-2398-11e8-9258-35fee56cdc27.png)

How i can fix this?

**Comment by carbontwelve** [comment] 2018-03-09 15:06
@goszowski I assumed (maybe incorrectly) that Laravel used `Illuminate\Http\UploadedFile` throughout for uploaded files and not `Symfony\Component\HttpFoundation\File\UploadedFile`. It seems in your case its passing the latter.

I have just pushed a new commit (d0c035c3d85f8b342c96b497c9c06016ce68eff7) to the 1.3.0-dev branch that should fix this for you.

Out of interest what version of Laravel are you using?

**Comment by goszowski** [comment] 2018-03-09 15:30
@carbontwelve 
Files are saved, but I can not check the existence of the file using the helper rememberedFile();
I don't know what key I can use. If this is "image[1]" or "image.1" then it does not work (returns null)

Screencast: https://www.youtube.com/watch?v=Qt1DI5PAoxk

![image](https://user-images.githubusercontent.com/10208931/37214466-ddc52652-23bd-11e8-9fc4-a8d31dd0cd85.png)

![image](https://user-images.githubusercontent.com/10208931/37214719-8674bd76-23be-11e8-9ec3-317d272e4650.png)

![image](https://user-images.githubusercontent.com/10208931/37214731-8e9cc52a-23be-11e8-95d8-63ae7c1a1416.png)

**Comment by goszowski** [comment] 2018-03-09 15:30
My Laravel version is 5.5

**Comment by goszowski** [comment] 2018-03-09 15:32
{{ dd($rememberedFiles) }} returns this:

![image](https://user-images.githubusercontent.com/10208931/37215162-dcb81f2e-23bf-11e8-8c67-3ea310fe3fa0.png)

**Comment by carbontwelve** [comment] 2018-03-09 16:00
@goszowski `rememberedFile()` on its own with no arguments should return an instance of `FileBag` with the remembered files inside it.

They are indexed by the inputs name, `$files = rememberedFile('image')` should return an instance of  `FileBag` which you should be able to do `$files->get(1)` to get the image for input named `image[1]` or `$files->all()` to get an array containing all the files for _image_.

**Comment by goszowski** [comment] 2018-03-09 17:11
@carbontwelve 
I made a simple test on clean laravel installation. Always returns NULL.
Now it does not even work with regular field names (not an array).

Screencast: https://www.youtube.com/watch?v=zowg-n3JdQU
Repo of this test (included photogabble/laravel-remember-uploads 1.3.0-dev): https://github.com/goszowski/remember-upload-test

**Comment by carbontwelve** [comment] 2018-03-09 19:22
@goszowski thank you. I was planning on creating a test install to reproduce your bug on but you beat me to it. I can see the issue and will fix asap.

**Comment by carbontwelve** [comment] 2018-03-09 20:00
@goszowski ok, the problem is that you are running the `remember.files` middleware on routes that it shouldn't run on.

It only needs to be applied to routes that are processing the upload  (e.g store, update in REST) and not on the route that displays the form.

With your example repository it is fixed with the `web.php` routes file being as such:

```php
Route::get('/', function () {
    return view('welcome');
});

Route::post('test', ['middleware'=>['remember.files'], 'as'=>'test', 'uses'=>'TestController@store']);
```

I have also tested your example repository with multiple file uploads by replacing the form content in `welcome.blade.php` with the following:

```php
<form action="{{ route('test') }}" enctype="multipart/form-data" method="post">
    {{ csrf_field() }}

    @if( $oldFile = rememberedFile('image'))
        <!-- $oldFile is now an array of Symfony\Component\HttpFoundation\File\UploadedFile -->
        <p>Image 0 Remembered: {{ $oldFile[0]->getFilename() }}</p>
        <p>Image 1 Remembered: {{ $oldFile[1]->getFilename() }}</p>
        <input type="hidden" name="_rememberedFiles[image][0]" value="{{ $oldFile[0]->getFilename() }}">
        <input type="hidden" name="_rememberedFiles[image][1]" value="{{ $oldFile[1]->getFilename() }}">
    @else
        <input type="file" name="image[0]">
        <input type="file" name="image[1]">
    @endif
    
    <button type="submit">Submit</button>
</form>
```

I think my documentation on this libraries readme needs some work because having re-read it, it isn't clear were the middleware needs to be applied.

**Comment by goszowski** [comment] 2018-03-10 08:34
@carbontwelve 
Working! Great work! Thank you!
I am waiting for release.

**Closed as completed** 2018-03-14 21:24 UTC
Labels: bug

**Comment by carbontwelve** [comment] 2018-03-14 21:31
@goszowski sorry for the delay, I got tied up with family matters. The 1.3.0 release containing this bugfix is now live https://github.com/photogabble/laravel-remember-uploads/releases/tag/1.3.0.

Thank you so much for your help and patience with this issue.
